# Generated by Django 4.1.7 on 2023-03-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='image',
        ),
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
